app/__init__.py
import logging
from multiprocessing.context import Process

from flask import Flask

from app.server import serve_runner

logger = logging.getLogger("main")
logger.setLevel(logging.DEBUG)

console_handler = logging.StreamHandler()
console_handler.setLevel(logging.DEBUG)
console_handler.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))

logger.addHandler(console_handler)


def create_app():
    app = Flask(__name__)

    logger.info("Server starting...")

    from app.routes import bp
    app.register_blueprint(bp)

    starting_port = 50052
    for port in range(starting_port, starting_port + 8):
        process = Process(target=serve_runner, args=(port,))
        process.start()

    return app

app/routes.py
from asgiref.sync import async_to_sync
from flask import Blueprint, jsonify, render_template, request

from app.client import run

bp = Blueprint("main", __name__)


@bp.route("/")
@bp.route("/index")
def index():
    return render_template("index.html"), 200


@bp.route("/multiply", methods=["POST"])
def multiply():
    matrix_1 = request.form.get("matrix_1", "", str)
    matrix_2 = request.form.get("matrix_2", "", str)

    if not (matrix_1 or matrix_2):
        return jsonify({"msg": "At least one matrix is missing, two matrices are required for multiplication."}), 400

    matrix_1 = [[int(item) for item in row.split(",")] for row in matrix_1.split(";")]
    matrix_2 = [[int(item) for item in row.split(",")] for row in matrix_2.split(";")]

    matrix_result = async_to_sync(run)(matrix_1, matrix_2, deadline=1)

    return jsonify({"result": ";".join([",".join([str(item) for item in row]) for row in matrix_result])}), 200

app/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link href="{{ url_for("static", filename="styles.css") }}" rel="stylesheet">

    <title>Matrix Calculator</title>
</head>
<body>

<div class="container pt-4">
    <section class="text-center">
        <h1>Matrix Calculator</h1>
        <h4 class="text-muted">Distributed Systems (ECS656U)</h4>

        <div class="alert alert-info mt-5 mx-auto">
            Please note that this calculator only supports matrix multiplication
        </div>
    </section>

    <section class="mt-5 text-center" id="input_section">
        <div class="row">
            <div class="col mb-3">
                <label for="input_file_1" class="form-label fw-bold">File 1</label>
                <input class="form-control" type="file" id="input_file_1" onchange="load_matrix(1)" required>
                <div class="valid-feedback">
                    Looks good!
                </div>
                <div class="invalid-feedback" id="input_1_invalid_feedback">
                    Missing file! Please select a matrix file to multiply.
                </div>

                <div id="input_1_table_container"></div>
            </div>

            <div class="col mb-3">
                <label for="input_file_2" class="form-label fw-bold">File 2</label>
                <input class="form-control" type="file" id="input_file_2" onchange="load_matrix(2)" required>
                <div class="valid-feedback">
                    Looks good!
                </div>
                <div class="invalid-feedback" id="input_2_invalid_feedback">
                    Missing file! Please select a matrix file to multiply.
                </div>

                <div id="input_2_table_container"></div>
            </div>
        </div>

        <div class="text-center my-4">
            <button class="btn btn-primary btn-lg fw-bold fs-3" onclick="calculate_matrix_multiplication()">
                Calculate
            </button>
        </div>
    </section>

    <section class="text-center my-5 d-none" id="output_section">
        <h3>Result!</h3>

        <div id="output_table_container"></div>

        <button class="btn btn-danger btn-lg fw-bold mt-4" onclick="window.location.reload();">Restart</button>
    </section>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>

<script>
    let matrix_1 = [];
    let matrix_2 = [];

    function load_matrix(matrix_num) {
        let input_1 = document.querySelector("#input_file_1");
        let input_2 = document.querySelector("#input_file_2");
        let matrix;
        let input;
        let table;

        {# TODO: ensure matrices are square #}
        {# TODO: ensure matrix dimensions are powers of 2 #}

        let reader = new FileReader();
        reader.onload = function () {
            let lines = this.result.split('\n');
            for (let line_no = 0; line_no < lines.length; line_no++) {
                let row = lines[line_no].replace("\r", "");

                if (/^(?=.*\d)[\d ]+$/.test(row))
                    matrix.push(row.split(" "));
                else {
                    matrix = [];

                    input.parentElement.querySelector(".invalid-feedback").innerText = "File could not be parsed! Ensure file is structured correctly.";
                    input.classList.remove("is-valid");
                    input.classList.add("is-invalid");

                    table.innerHTML = "";

                    return;
                }
            }

            if (matrix.length !== matrix[0].length || (matrix.length & (matrix.length - 1)) !== 0) {
                matrix = [];

                input.parentElement.querySelector(".invalid-feedback").innerText = "Matrix must be square and its dimensions must be a power of 2!";
                input.classList.remove("is-valid");
                input.classList.add("is-invalid");

                table.innerHTML = "";

                return;
            }

            build_table(table, matrix);
        };

        if (matrix_num === 1) {
            matrix = matrix_1 = [];
            input = input_1;
            table = document.querySelector("#input_1_table_container");

            reader.readAsText(input_1.files[0]);

            input_1.classList.remove("is-invalid");
            input_1.classList.add("is-valid");
        } else {
            matrix = matrix_2 = [];
            input = input_2;
            table = document.querySelector("#input_2_table_container");

            reader.readAsText(input_2.files[0]);

            input_2.classList.remove("is-invalid");
            input_2.classList.add("is-valid");
        }
    }

    function calculate_matrix_multiplication() {
        let input_1 = document.querySelector("#input_file_1");
        let input_2 = document.querySelector("#input_file_2");
        let valid = true;

        if (matrix_1.length === 0) {
            input_1.parentElement.querySelector("#input_1_invalid_feedback").innerText = "Missing file! Please select a matrix file to multiply.";
            input_1.classList.remove("is-valid");
            input_1.classList.add("is-invalid");
            valid = false;
        }

        if (matrix_2.length === 0) {
            input_2.parentElement.querySelector("#input_2_invalid_feedback").innerText = "Missing file! Please select a matrix file to multiply.";
            input_2.classList.remove("is-valid");
            input_2.classList.add("is-invalid");
            valid = false;
        }

        if (!valid) return;

        let form_data = new FormData();
        form_data.append('matrix_1', matrix_1.map(e => e.join(',')).join(';'));
        form_data.append('matrix_2', matrix_2.map(e => e.join(',')).join(';'));

        fetch("{{ url_for("main.multiply") }}", {
            method: "POST",
            body: form_data
        })
            .then(response => response.json())
            .then(function (data) {
                console.log(data);

                document.querySelector("#input_section").classList.add("d-none");
                build_table(document.querySelector("#output_table_container"), data["result"].split(";").map(e => e.split(",")));
                document.querySelector("#output_section").classList.remove("d-none");
            })
        {# TODO: add error handling #}
    }

    function build_table(table, matrix_data) {
        let table_html = '<table class="table table-bordered w-auto mx-auto mt-4 fw-bold"><tbody>'

        if (matrix_data.length <= 5)
            matrix_data.forEach(function (row) {
                table_html += `<tr>`;
                row.forEach(function (item) {
                    table_html += `<td class="pt-4 fs-5" style="width: 4em !important; height: 4em;">${item}</td>`
                })
                table_html += `</tr>`;
            });
        else
            for (let row = 0; row < 5; row++) {
                table_html += `<tr>`;
                if (row < 2 || row > 2)
                    for (let col = 0; col < 5; col++) {
                        let td;

                        if (col === 2)
                            td = '...';
                        else {
                            let row_addr;
                            let col_addr;

                            if (row > 2)
                                row_addr = matrix_data.length - (5 - row);
                            else
                                row_addr = row;

                            if (col > 2)
                                col_addr = matrix_data.length - (5 - col);
                            else
                                col_addr = col;

                            td = matrix_data[row_addr][col_addr];
                        }

                        table_html += `<td class="pt-4 fs-5" style="width: 4em !important; height: 4em;">${td}</td>`;
                    }
                else
                    for (let col = 0; col < 5; col++)
                        table_html += `<td class="pt-4 fs-5" style="width: 4em !important; height: 4em;">...</td>`;
                table_html += `</tr>`;
            }

        table_html += '</tbody></table>';

        table_html += `<span class="fw-bold">${matrix_data.length}x${matrix_data[0].length}</span>`;

        table.innerHTML = table_html;
    }
</script>
</body>
</html>